Fix copyright date
lf-edge/edge-home-orchestration-go pull request #157
Opened 2020-10-29 06:11 UTC by tdrozdovsky

Signed-off-by: Taras Drozdovskyi <t.drozdovsky@samsung.com>

# Description

The correction concerns the copyright date. Since according to the rules, after changing the file, the year of change is added and not corrected. for example the file was created in 2016, in 2019 and in 2020 was edited then the entry should be 2016, 2019-2020.
This must be strictly followed as this can lead to ownership disputes.

P.S. If you know more files where this was fixed from 2019 to 2020, please make the edits.

## Type of change

- [x] Code cleanup/refactoring

# Checklist:

- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2020-10-30 01:08 UTC, MoonkiHong commented
@tdrozdovsky Thank you. Will back to you soon after our `Coconut` release.

2020-11-02 00:09 UTC, MoonkiHong reviewed
@tdrozdovsky Please see my comment (for a suggestion to revise)

2020-11-02 00:09 UTC, MoonkiHong commented on src/interfaces/capi/main.go
> +// * Copyright 2019-2020 Samsung Electronics All Rights Reserved.
@tdrozdovsky What about removing this statement due to the duplication of the state at the header?

2020-11-03 13:02 UTC, tdrozdovsky commented on src/interfaces/capi/main.go
> +// * Copyright 2019-2020 Samsung Electronics All Rights Reserved.
I believe that this is a duplication, but on the other hand it is an attachment of С file that has its own license.

I didn't create this file and I don't know what the author meant. So I left the code unchanged.

2020-11-03 23:40 UTC, MoonkiHong commented on src/interfaces/capi/main.go
> +// * Copyright 2019-2020 Samsung Electronics All Rights Reserved.
@tdrozdovsky Uhm... This is not a matter of who creates the file, but the original proposal of this PR is to rectify the copyright statement of each updated / created file in our project and I do not believe that the current 19 files are not created from you, but appreciatively, your PR suggests to rectify the statement. 

All the copyright statements of the files in our project are described at the top most of each file and there is no exception.

2020-11-03 23:41 UTC, MoonkiHong requested changes
PTAL.

2020-11-04 06:51 UTC, tdrozdovsky commented on src/interfaces/capi/main.go
> +// * Copyright 2019-2020 Samsung Electronics All Rights Reserved.
@MoonkiHong I've removed the Copyright header.

2020-11-04 07:27 UTC, MoonkiHong approved these changes
LGTM.

2020-11-04 08:42 UTC, suresh-lc approved these changes
Thanks for incorporating in all 19 files

2020-11-04 11:54 UTC, merged