[Builder] Moved DataStorage init and configuration to builder
lf-edge/edge-home-orchestration-go pull request #187
Opened 2020-11-27 09:45 UTC by sun-sharma

Added code to initialize Datastorage in builder

Signed-off-by: Sunchit Sharma <sun.sharma@samsung.com>

# Description
Changes made to move Data Storage Conf. to Builder

Fixes  #137 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code cleanup/refactoring
- [ ] Documentation update
- [ ] This change requires a documentation update

# How Has This Been Tested?
Tested normal flow of Data Storage

**Test Configuration**:
* Firmware version: Ubuntu 16.04
* Edge Orchestration Release:  Coconut

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2020-11-27 12:47 UTC, t25kim requested changes
Thank you for this PR.
I'm sorry for the misunderstanding caused by the lack of details.
#137 is not intended to implement the storagemgr in the orchestrationapi.
We should create the storagemgr.go file in the controller/storagemgr folder and implement source code like the [discoverymgr](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/src/controller/discoverymgr/discovery.go).
Please take a close look at the other managers such as discoverymgr, servicemgr, etc.

2020-11-27 12:47 UTC, t25kim commented on GoMain/src/main/main.go
> +	storageIns := internalapi.GetStorageInstance()
If the configuration.toml file is not in dataStorageFilePath like #159, is it working?

2020-11-27 12:47 UTC, t25kim commented on src/orchestrationapi/orchestration.go
> +	storageDriverIns   storagedriver.StorageDriver
The orchestrationapi is not the storagemgr, we should implement storagemgr in src/controller/storagemgr/.
Please refer to the [discoverymgr](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/src/controller/discoverymgr/discovery.go) when you implement the storagemgr.

2020-11-27 12:47 UTC, t25kim commented on GoMain/src/main/main.go
> +	go startup.Bootstrap(dataStorageService, device.Version, &storageIns)
I think we should initiate the storagemgr at the [orchestrationapi](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/src/orchestrationapi/orchestration.go).
Please refer to the [Start](https://github.com/lf-edge/edge-home-orchestration-go/blob/a2359b166b40ed829e8bb771ccfd7af7032d1244/src/orchestrationapi/orchestration.go#L188) function for discoverymgr.

2020-11-27 12:47 UTC, t25kim commented on GoMain/src/main/main.go
> +	if _, err := os.Stat(dataStorageFilePath); err == nil {
We should move this code to the storagemgr.

2020-11-30 01:40 UTC, MoonkiHong reviewed
@sun-sharma Thank you for your proposal. The current reported issue #137 is to setup the dedicated manager for `Data Storage` like others such as `discoverymgr`, `servicemgr`, and `securitymgr`. We are very sorry to give this miscommunication to you, and please refer to the review comments from @t25kim. We are always appreciating your passionate contributions into our community.

2020-11-30 10:35 UTC, sun-sharma commented
Thank you for the review. I went through all the changes suggested and would follow the required changes and structure and try to re raise a PR.

2020-12-07 10:33 UTC, sun-sharma commented
I am closing this PR and raising another as many changes on this code have been overwritten.

2020-12-07 10:33 UTC, closed without merging