Replaced the "os" (ubuntu-18.04) for CI build, test-suite with a newe…
lf-edge/edge-home-orchestration-go pull request #614
Opened 2022-08-24 10:48 UTC by tdrozdovsky

…r one (ubuntu-22.04)

Signed-off-by: Taras Drozdovskyi <t.drozdovsky@samsung.com>

# Description

Due to the ubuntu 18.04 is deprecated, it was replaced with ubuntu 22.04 for CI.

Fixes #612 

## Type of change

- [x] CI system update

**Test Configuration**:
* OS type & version: Ubuntu 20.04
* Hardware: x86-64
* Toolchain: Docker v20.10 & Go v1.16
* Edge Orchestration Release: v1.1.16

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-08-24 10:53 UTC, t25kim commented
What about updating `ubuntu` and `ubuntu_multistage` in [defdockerfiles](https://github.com/lf-edge/edge-home-orchestration-go/tree/master/configs/defdockerfiles) with 22.04?

2022-08-24 11:33 UTC, tdrozdovsky commented
> What about updating `ubuntu` and `ubuntu_multistage` in [defdockerfiles](https://github.com/lf-edge/edge-home-orchestration-go/tree/master/configs/defdockerfiles) with 22.04?

If it is necessary to update the base OS then I suggest using 20.04

2022-08-25 00:30 UTC, t25kim commented
> If it is necessary to update the base OS then I suggest using 20.04

20.04 is also fine!

2022-08-25 07:46 UTC, t25kim approved these changes
LGTM

2022-08-28 23:38 UTC, t25kim requested changes
It looks like there are a lot of things to check to include 22.04.

2022-08-29 05:46 UTC, tdrozdovsky commented
> It looks like there are a lot of things to check to include 22.04.

Yes, you are absolutely right, additional study is needed for the 22.04 version. That's why I didn't want to use it as a base image. I hope soon I will be able to study 22.04 in more detail and adjust it for successful check of the our project

2022-08-29 05:53 UTC, t25kim commented
Let's use only 20.04 now. Please revise the commit message as well.

2022-08-29 10:19 UTC, tdrozdovsky commented
> Let's use only 20.04 now. Please revise the commit message as well.

Done!

2022-08-29 10:38 UTC, MoonkiHong approved these changes
+1

2022-08-29 10:50 UTC, t25kim approved these changes
LGTM! Thanks!

2022-08-31 23:51 UTC, merged